name: PyInstall!
run-name: Deploy! 🚀
on: [push]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'src/main.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'AWC'
          options: --onedir, --name "AWC1", --console, 
