name: PyInstall!
run-name: Deploy! 🚀
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'AWC'
          options: --onefile, --name "AWC", --console, 
